/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddFoodForm: typeof import('./src/lib/features/fridge/crud/AddFoodForm.vue')['default']
    AddIcon: typeof import('./src/lib/ui/icon/AddIcon.vue')['default']
    AddLogEntryForm: typeof import('./src/lib/features/log/crud/AddLogEntryForm.vue')['default']
    AuthForm: typeof import('./src/lib/features/auth/AuthForm.vue')['default']
    BackArrowIcon: typeof import('./src/lib/ui/icon/BackArrowIcon.vue')['default']
    CrossIcon: typeof import('./src/lib/ui/icon/CrossIcon.vue')['default']
    DailyLog: typeof import('./src/lib/features/log/overview/DailyLog.vue')['default']
    EditFoodForm: typeof import('./src/lib/features/fridge/crud/EditFoodForm.vue')['default']
    EditIcon: typeof import('./src/lib/ui/icon/EditIcon.vue')['default']
    EditLogEntryForm: typeof import('./src/lib/features/log/crud/EditLogEntryForm.vue')['default']
    FoodDetailsEditor: typeof import('./src/lib/features/fridge/crud/components/FoodDetailsEditor.vue')['default']
    FoodFormView: typeof import('./src/lib/features/fridge/crud/FoodFormView.vue')['default']
    FoodIcon: typeof import('./src/lib/ui/icon/FoodIcon.vue')['default']
    FoodNutrientsEditor: typeof import('./src/lib/features/fridge/crud/components/FoodNutrientsEditor.vue')['default']
    FoodSearchResults: typeof import('./src/lib/features/fridge/search/FoodSearchResults.vue')['default']
    FoodServingsEditor: typeof import('./src/lib/features/fridge/crud/components/FoodServingsEditor.vue')['default']
    FormNavigationBar: typeof import('./src/lib/ui/form/nav/FormNavigationBar.vue')['default']
    ForwardArrowIcon: typeof import('./src/lib/ui/icon/ForwardArrowIcon.vue')['default']
    FridgeSection: typeof import('./src/lib/features/fridge/FridgeSection.vue')['default']
    GitHubSignInButton: typeof import('./src/lib/ui/ext/GitHubSignInButton.vue')['default']
    GoogleSignInButton: typeof import('./src/lib/ui/ext/GoogleSignInButton.vue')['default']
    Header: typeof import('./src/lib/features/layout/Header.vue')['default']
    ImageInput: typeof import('./src/lib/ui/form/input/ImageInput.vue')['default']
    InteractableItem: typeof import('./src/lib/ui/list/InteractableItem.vue')['default']
    LabeledHorizontalRule: typeof import('./src/lib/ui/util/LabeledHorizontalRule.vue')['default']
    LabeledInput: typeof import('./src/lib/ui/form/input/labeled/LabeledInput.vue')['default']
    LabeledNumberInput: typeof import('./src/lib/ui/form/input/labeled/LabeledNumberInput.vue')['default']
    LabeledSelect: typeof import('./src/lib/ui/form/input/labeled/LabeledSelect.vue')['default']
    ListLoadingEffect: typeof import('./src/lib/ui/list/ListLoadingEffect.vue')['default']
    LoadingEffect: typeof import('./src/lib/ui/util/LoadingEffect.vue')['default']
    LogEntryFormView: typeof import('./src/lib/features/log/crud/LogEntryFormView.vue')['default']
    LogItem: typeof import('./src/lib/ui/list/LogItem.vue')['default']
    LogSection: typeof import('./src/lib/features/log/LogSection.vue')['default']
    NutritionalInfo: typeof import('./src/lib/features/log/crud/components/NutritionalInfo.vue')['default']
    Prompt: typeof import('./src/lib/ui/util/Prompt.vue')['default']
    RecipeIcon: typeof import('./src/lib/ui/icon/RecipeIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/lib/features/fridge/search/Search.vue')['default']
    SearchInput: typeof import('./src/lib/ui/form/input/SearchInput.vue')['default']
    Shadeout: typeof import('./src/lib/ui/util/Shadeout.vue')['default']
    SomaBackground: typeof import('./src/lib/features/auth/SomaBackground.vue')['default']
    SomaLogoIcon: typeof import('./src/lib/ui/icon/SomaLogoIcon.vue')['default']
    SwipeableItem: typeof import('./src/lib/ui/list/SwipeableItem.vue')['default']
    TabSelection: typeof import('./src/lib/ui/list/TabSelection.vue')['default']
    TargetsForm: typeof import('./src/lib/features/analysis/targets/TargetsForm.vue')['default']
    TargetsProgress: typeof import('./src/lib/features/log/overview/targets/TargetsProgress.vue')['default']
    TransparentButton: typeof import('./src/lib/ui/action/TransparentButton.vue')['default']
    TrashIcon: typeof import('./src/lib/ui/icon/TrashIcon.vue')['default']
  }
}
